[project]
name = "fleetingviewslogintemplate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fleetingviews>=0.1.9.post2",
    "pip>=25.1.1",
]
